### ISSUE TITLE
mau-mau time_durations crashes on Windows 10 (i should switch my OS :-D)

### ISSUE THREAD

**Issue by gregcodes** [obestwalter/mau-mau#10]
```
Traceback (most recent call last):
      File "C:\Users\Grigori\mau-mau-venv\Scripts\mau-mau-script.py", line 9, in <module>
        load_entry_point('mau-mau==4.0.0', 'console_scripts', 'mau-mau')()
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\cli.py", line 54, in main
        functionObject(*args)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\stats.py", line 30, in time_durations
        number=number)
      File "C:\Program Files (x86)\Python 3.5\lib\timeit.py", line 213, in timeit
        return Timer(stmt, setup, timer, globals).timeit(number)
      File "C:\Program Files (x86)\Python 3.5\lib\timeit.py", line 178, in timeit
        timing = self.inner(it, self.timer)
      File "<timeit-src>", line 3, in inner
    ImportError: No module named 'mau_mau.main'

```

**Comment by obestwalter** [comment]
Ahh ..this was actually an os indepedent bug and was fixed in https://github.com/obestwalter/mau-mau/commit/96ba2cf979ff3740b429e5dfae27995090418cf4
