### ISSUE TITLE
mau-mau human crashes immediately on Windows 10

### ISSUE THREAD

**Issue by gregcodes** [obestwalter/mau-mau#9]
```
Traceback (most recent call last):
      File "C:\Users\Grigori\mau-mau-venv\Scripts\mau-mau-script.py", line 9, in <module>
        load_entry_point('mau-mau==4.0.0', 'console_scripts', 'mau-mau')()
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\cli.py", line 54, in main
        functionObject(*args)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\cli.py", line 26, in play_interactive_game
        playedGame = play.play_game(_rulesOfTheGame, ['Eric', 'John', 'human'])
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\play.py", line 12, in play_game
        player.play(game.table)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\subjects.py", line 91, in play
        self.strategy.play(table)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\strategy.py", line 25, in play
        self._play(table, card)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\strategy.py", line 57, in _play
        card = self.choose_best_candidate(candidates)
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\strategy.py", line 94, in choose_best_candidate
        return cls.get_valid_choice(cards, "choose card to play")
      File "c:\users\grigori\mau-mau-venv\lib\site-packages\mau_mau\strategy.py", line 109, in get_valid_choice
        idx = input("%s.\n%s | " % (msg, visu(choices)))
      File "C:\Program Files (x86)\Python 3.5\lib\encodings\cp850.py", line 12, in encode
        return codecs.charmap_encode(input,errors,encoding_map)
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2663' in position 37: character maps to <undefined>

```

**Comment by ghost** [comment]
Issue can be closed after my [pull request](https://github.com/obestwalter/mau-mau/pull/13/commits/7efc8f2cae3ea8da64078b6dea6697d609c84626).

**Comment by obestwalter** [comment]
Thanks!
